### ISSUE TITLE
no support for filmstrip knobs

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/dplug#148]
This would greatly improve the functionality of the library

**Comment by p0nce** [comment]
You mean knobs with each image pre-rendered?

**Comment by abaga129** [comment]
Yes exactly, from what I can tell there isn't any support for this right now.  It would be great to be able to use knobs rendered from knobman or made in photo editors.

**Comment by p0nce** [comment]
Hi @abaga129 ,

One of the objective of Dplug,'s renderer is to avoid pre-rendered graphics and render them instead dynamically. You probably have seen a rationale in https://www.auburnsounds.com/blog/2016-09-16_PBR-for-Audio-Software-Interfaces.html
So Dplug works with 9 channels instead of R, G, B and it's more complicated.
See here about the detailed process of creating a PBR GUI: 
It's work, takes me 1 month.

Currently there isn't much knob style available, my goal is to allow to make new knob styles with a few images concatenated (diffuse, material, opacity...) and rotate them. Similar to how `tools/pbr-sketch` work.

However, as of today this whole PBR business can be bypassed if you output 0 in the Physical channel. 
So eg. you could make a more flat design and control directly the final color, which is valuable.

If you want such a Knob, you can make your own UI widget similar to `dplug.gui.knob.UIKnob` and in the `onDraw` function fills the graphics with your prerended image from Knobman. 

```
override void onDraw(ImageRef!RGBA diffuseMap, ImageRef!L16 depthMap, ImageRef!RGBA materialMap, box2i[] dirtyRects) nothrow @nogc
{
    // fill diffuseMap in the following way: R, G and B takes the desired color
    // fills materialMap in the following way: A takes 0.
}
```

So you can derive from UIElement to make such a filmstrip knob.
Or perhaps derive from `UIBufferedElement` which lets you control the blending more and avoids the `dirtyRects` limitation. Let me know if you need more.

Note than when bypassing PBR you still get global color correction.

**Comment by abaga129** [comment]
Thanks a lot for the indepth explanation!  This is an excellent library and im greatful that you made it open source. I had a feeling it would be possible to inherit from UIKnob I just wasnt sure.  I will definitely take a look more into it.

**Comment by p0nce** [comment]
`UIKnob` would not be the one to inherit from (it has many fields because of prodedural generation) but non-rendering code in it can be copied yes.

**Comment by p0nce** [comment]
Closing this ticket since filmstrip knobs will have nothing over 9-channels rotated knobs ;)
