### ISSUE TITLE
Principled rasterizer

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#164]
`draw.d` and `drawex.d` have grown unprincipled, with many one-shot functions.
Introduces a principled rasterizer base on 2D bezier curve and paths, with an API much like HTML Canvas or other typical drawing APIs.
This rasterizer should work on any image type.

**Comment by p0nce** [comment]
A library like skia or cairo may actually make more sense that the pure genericity of ae-graphics

**Comment by detomastah** [comment]
Seems that cairo already has bindings, so it might be better suited for this task?

**Comment by p0nce** [comment]
The problem with D and embedding a (big) static library: 
- on Windows you need to come with both COFF and OMF .lib (if you want to use DMD). Where to put them? There is no system package manager so you would commit them in Dplug, and suddenly Dplug is huge to download and has license problems.
- also your library gets embedded many times (each configuration of a plugin x formats x bitness) so it rather be small. Right now a version of say Graillon takes about 1mb per binary zipped, and it's very practical.
- also need working symbol stripping, which is very manual on macOS and not yet done in Linux, else you could "overlink"
- also if it's LGPL, not going to cut it

The problem with D and embedding a dynamic library:
- VST plugins wouldn' be one file anymore on Windows
- you pay the maximum price in binary size,  For the same reasons we refused the runtime being in a dynlib (would make final archives 3x larger).

That's why Dplug tend to use a minimum of anything.

**Comment by p0nce** [comment]
It sounds like "cerjones" on Discord had something very interesting (a fast pure D rasterizer)

**Comment by p0nce** [comment]
Roughly usable now, see the ClipIt example to see how. Allocations should be all amortized if you it this way.

**Comment by p0nce** [comment]
Note that having things like HTML Canvas "stroke()" is more involved than expected, it needs a Path abstraction, and .
Regardless, proper bezier curves + matrix transformation also need a path abstraction, in order to flatten it to edges.

**Comment by dewf** [comment]
(Sorry to resurrect this issue, but I meant to reply "someday", before getting sidetracked on some projects that took me away from D)

It's been a long time since I advertised it on the D newsgroups (trying to court any would-be GUI developers), but did you ever come across my [OpenDL library](https://github.com/dewf/opendl)? There's probably a 95% chance it won't fit with the needs of DPlug, but nonetheless I wanted to make sure you knew of its existence before the point of no return on the new canvas API (and apologies if you've already fully committed to that route).

Basic overview:
- C API for easy D consumption (written for my own D project, in progress)
- GPU-accelerated for free on Mac/Windows because of reliance on native APIs
- text rendering via Core Text / DirectWrite / Pango
- Quartz API is super clean and canvas-like. Great documentation via Apple.
- easy to verify Win/Linux functionality since I can always just compare with Mac output for correctness.
- reasonably small, since I'm just riding on top of platform-specific APIs. Windows 64-bit release DLL is ~150K, .LIB file is ~40K. Not sure about Mac/Linux offhand but should be considerably smaller (because the Windows code does a lot of COM wrangling)
- though currently configured as a shared lib, no reason it couldn't be statically linked instead. (TODO: migrate everything to CMake)

Issues with respect to some of your points above:
- though OpenDL is MIT licensed, I don't know how the Cairo reliance on Linux might affect things. I don't know anything about the portability of shared libs across modern linux distributions. ie, is it possible to dynamically link to Cairo/Pango on one system, and have it work everywhere else? Or does LGPL allow distributing the shared library itself (eg, a specific Cairo .so version)?
- I'm clueless about symbol stripping, no idea if that's already a dealbreaker in this case.
- written internally in C++, not D. As I explained on the D 'announce' newsgroup [back when I advertised it](https://forum.dlang.org/post/qpekvdwnsgqulbwkduxf@forum.dlang.org), I went that route because (particularly with COM) it was just easier to use the native tools (Visual Studio / XCode) and not have to translate headers. I was also writing this alongside OpenWL, which did require a lot of Objective-C for the Mac side. I was/am too much of a D amateur to have accomplished all of this in pure D. That said, I guess an enterprising D dev could take what I've written and port it for a 100% D-native alternative - it's not THAT much code.
- some issues with fallback font metrics on Linux, relative to Mac/Windows. Short of writing my own text layout engine to replace reliance on DirectWrite and Pango (someday!), there's probably not much I can do about it.
- due to reliance on a particular DirectWrite version, it won't currently work on older versions of Windows (7 / 8.1). It's been a long time since I looked at it, but IIRC there was one DirectWrite API call in particular that if I could get rid of, I might be able to support Win7 SP1, or at least 8.1.
- if the US Supreme Court rules in favor of Oracle (in the Java API case, vs. Google), Apple could send its lawyers after anybody copying their APIs. But that's looking [increasingly unlikely](https://www.zdnet.com/article/google-vs-oracle-the-next-chapter/).

cheers!

**Comment by 0xEAB** [comment]
> written internally in C++

so I'd need to setup a C++ toolchain to make this work, wouldn't I?

##### Cairo

> I don't know how the Cairo reliance on Linux might affect things. 

I'll quote @p0nce on that:

> also if it's LGPL, not going to cut it

on the other hand, MPL (second license option of Cairo) isn't that handy either for audio plugins

**Comment by p0nce** [comment]
Hello @dewf ,

We haven't put anything written in C++ or Obj C to keep thing simple with DUB.

In general we try to :
- use symbol loading like BindBC everywhere if this is a system library
- use statically linked D code if this is a custom library. 
The only exception is X11 and this has caused problems with DUB since you can't have `"dependencies-<platform>"`.

Dplug is generally not all-inclusive at all, it has the limited goal of making plug-ins work with minimal maintenance on desktop computers.
Typically we use the minimum amount of system APIs, and as such`dplug:canvas` itself is limited to a few things that work well.
I agree that using native libraries them should be fast and take less code size. But (at least for me) I wasn't really looking for a better solution, rather a 80% solution.

I feel that it might be interesting for the GLIMPSE project, seeing how things look nicely decoupled! It should be a good fit for many projects. I do'nt think there is a lot of such projects who abstract over the platform 2D drawing API (SDL renderers? Java AWT?)

**Comment by dewf** [comment]
@0xEAB 
> so I'd need to setup a C++ toolchain to make this work, wouldn't I?

Well, not necessarily. A "batteries-included" Dub package would contain the compiled .lib files, so D developers / build-from-source end users wouldn't have to mess with C++ at all. However, statically-linked binary distribution on Linux is still a problem because of the Cairo license. 😬 . I really don't follow the Linux world so I have no idea if or how things like Flatpak might address shared library distribution, which might be enough to satisfy the LGPL.

@p0nce - Thanks for having a look!
