### ISSUE TITLE
LV2/LADSPA/DSSI Linux Plugin support

### ISSUE THREAD

**Issue by MartinNowak** [AuburnSounds/dplug#179]
Also any interest in [LV2](http://lv2plug.in/) support?

**Comment by p0nce** [comment]
Well, not from me.
Linux accounts for maybe 2% of audio users, but the complexity is staggering honestly. 4 plugin formats, VST variation from Ardour, and X11 should be loaded dynamically in the first place. This looks like a money sink when there are much more people asking for AAX.

**Comment by p0nce** [comment]
Side note: only major dominant player can ever hope to have their format succeed. Steinberg pushed VST3 hard and no one customer is asking for it even years later, and Reason abandonned ReFX recently in favour of VST2

**Comment by abaga129** [comment]
An LV2 client is now in the works.  I will be tracking the progress on  #307. I dont see any benefit from LADSPA/DSSI since LV2 is the spiritual successor to both.  There seems to be some interest in LV2 atleast from a developer standpoint.  I'm not sure how many users will desire the LV2 format but I think the benefit of having an option that is open and cross-platform is worth the time to develop.
