### ISSUE TITLE
Importing png image causes distorted UI on linux

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#206]
This seems to be a very particular case.  The problem was narrowed down to the following statement.
```D
OwnedImage!RGBA bipolarKnobImage = loadOwnedImage(cast(ubyte[])(import("bipolar.png")));
```
This causes the entire UI to have a glowing look to it which I'm assuming has something to do with the emmisive map, and leaves short black horizontal lines all over the it.

I will try a different png file when I get a chance to see if it is specific to that file.  Could this be an alignment issue?

Also an important note is that it is not the only image being imported.

**Comment by p0nce** [comment]
Hard to know without the image, reproducible test sample or a screenshot.

**Comment by abaga129** [comment]
![dplug-bug-distortedui](https://user-images.githubusercontent.com/8194039/32904708-994e1bea-cabd-11e7-8415-c6c468f22a72.png)
![knobbi](https://user-images.githubusercontent.com/8194039/32904731-b10787c6-cabd-11e7-9083-8247de50a33a.png)
Here is a screenshot of the plugin experiencing the problem, and I've added the image that is being imported also.

**Comment by p0nce** [comment]
OK so I have questions:
- [ ] Is is still the same on another OS?
- [ ] If the problem image is the knob, how come the rest of the window is affected
- [ ] I assume yo uhave a background PNG, could you also post it?
- [ ] If yes, in which order do you load them?

Please also post the other PNG you are importing, it could be that the knob image trips up the decoder for further values.

**Comment by abaga129** [comment]
Apologies for my lack of describing the problem.
"Is is still the same on another OS?"  
One user has reported a similar fault on windows but was unable to reproduce it, and I haven't been able to either.  I haven't seen it on OS X yet.

"If the problem image is the knob, how come the rest of the window is affected" 
I cant explain this.  Even if I just import the knob image and don't use it, this still occurs.  In the screenshot above, the actual image is not being drawn anywhere on the screen.

"I assume yo uhave a background PNG, could you also post it?"
Yes here it is
![background](https://user-images.githubusercontent.com/8194039/32958090-0e2c0312-cb83-11e7-8d9d-7f27a15ce4b7.png)

There is also another knob Image being imported.
http://www.modernmetalproduction.com/wp-content/uploads/2017/11/knobOrange.png
 
"If yes, in which order do you load them?"
The order is as follows
- background.png (name passed as template param to FlatBackgroundGUI)
- knobBi.png (The image causing the problem)
- knobOrange.png

**Comment by p0nce** [comment]
> One user has reported a similar fault on windows but was unable to reproduce it, and I haven't been able to either.  I haven't seen it on OS X yet.

This weakly points towards memory errors.

> I cant explain this.  Even if I just import the knob image and don't use it, this still occurs.  In the screenshot above, the actual image is not being drawn anywhere on the screen.
> The order is as follows
> - background.png (name passed as template param to FlatBackgroundGUI)
> - knobBi.png (The image causing the problem)
> - knobOrange.png

What is extremely strange is that the image that cause your problem is loaded after the area that seems corrupted on screen.

So a bit of summing up:

- we don't really know if it's linux specific however users are often surprisingly accurate about bugs so I'll be assuming that it's not OS related, hence not X11 related.

- in your screenshot it's pretty clear that knobs are glowing as if Emissive is > 0 and Physical is 255. Actually it feels like your whole materialMap is filled with uninitialized data.

The problem is readily apparent here in 
https://github.com/AuburnSounds/Dplug/blob/master/flatwidgets/dplug/flatwidgets/flatbackgroundgui.d#L48

You have to fill the material map with RGBA(?, ?, ?, 0); so that Physical is 0 (you can leave the depth map untouched.

**Comment by p0nce** [comment]
Most probably we fell victim to malloc initializing memory to 0 and us unknowingly relying on it.

**Comment by p0nce** [comment]
Waiting for your PR :)

**Comment by abaga129** [comment]
Ah thanks for looking into it! I always just assumed the maps were initialized and filled with 0s.
I will confirm the fix and make a PR as soon as possible!

**Comment by p0nce** [comment]
I know it will feel contrived but no the maps are not initialized. The reasoning (if there was one at all) was probably that 
1. you need a background widget
2. such a widgets would need to reinitialize the map since they can be overwritten by elements higher in the stack
3 hence initializing it was not needed.

I'll add a comment on the onDraw of background widgets to make it clear all maps have to be filled.

**Comment by abaga129** [comment]
I can confirm that it fixed the problem! I made a pull request. I went ahead and made a comment on `FlatbackgroundGUI` that the maps need to be filled.
Thanks!
