### ISSUE TITLE
dplug:window's mess: clarify roles between window, plugin window and host window

### ISSUE THREAD

**Issue by rikkimax** [AuburnSounds/Dplug#221]
The current state of the OSX window implementation leaves much to be desired in terms of a windowing library.

Unlike Windows and X11 support, it does not follow the same line of working.
It is much more like an application code instead of a library.

The window example will not work here for this reason, which means that code that works on one platform will not operate the same way on another.

**Comment by p0nce** [comment]
What are you thinking of specifically?

**Comment by rikkimax** [comment]
Being able to create a window without a parent, should work as in the window example.

No parent, no host. I am simply afraid when looking at it that it may be too use-case specific.
It probably can be fixed in the existing code.

**Comment by p0nce** [comment]
TODO: fix window example for Cocoa

**Comment by p0nce** [comment]
The problem is that the calls

```
void onDraw(WindowPixelFormat pf);
ImageRef!RGBA onResized(int width, int height);
void recomputeDirtyAreas();
box2i getDirtyRectangle();
void onAnimate(double dt, double time);
```

only make sense originally in the context of plug-in window inside a host window, and IWindow was hijacked later to act as a host window itself.

It make no real sense for such a top-level window to have this particular `onDraw` so the listener hack was found to distinguish top-level inert window from plugin windows.

That was why the window example was deleted at one point, because you would implement those 5 non-sensical functions.

To fix this bug properly you would need to disentangle "all purpose" windows, and "plug-in" windows. Plug-in behaviour would hopefully pass into GUIGraphics but more realistically in a platform-specific middle ground.

**Comment by rikkimax** [comment]
Yes, this issue popped up with X11, mixed threading, very bad.

Because of the way host versus plugin work, all windows should probably be owned by its own little thread like in Java. But it would be a bit of working making that play well with say a plugin and drawing.

**Comment by p0nce** [comment]
This problem came a second time, it comes up everytime someone want to fix X11 windowing. 

Here is a proposal to get out of the semantic blurriness we're in, using more types.

- [ ] "Purpose" of a window is passed at creation time in `createWindow`:
```d
enum WindowPurpose
{
    // This window is used inside a plug-in host
    purposePlugin,

    // There is no plugin host this window is created in
    purposeHost,    
```

"Purpose" will help disciminate what happens in X11 windowing.
This purpose cannot be inferred solely from window parenting (X11 plugin window have no parents) or listener (because at least the `window` test need a listener).

- [ ] Listener is assumed to never be `null`. However there can be a `NullWindowListener` ready-made in `dplug:window`.

What do you think?

**Comment by detomastah** [comment]
I like this idea, because it is possible to introduce this without modifying window implementations. It will also help me with X11. So I'm for it.

**Comment by rikkimax** [comment]
WindowUsage/WindowPurpose sounds good.

But in saying this, why is the parent window not being passed to the implementation anyway?
It should be disabled at the implementation side if it must be, not on the callers side.

**Comment by detomastah** [comment]
```
This purpose cannot be inferred solely from window parenting (X11 plugin window have no parents)
```
Sorry guys, I'm new to VSTs but what is the reason for this? Is this true for all LInux VST hosts?

**Comment by p0nce** [comment]
> But in saying this, why is the parent window not being passed to the implementation anyway?

I don't understand your question. Which implementation? "parent window" exists for Win32 with plugin purpose, in Carbon it's a pair of handles, and in Cocoa it's like Win32 host windows have no parent. For X11 I'm unsure. "purpose" can't be derived from either the listener or whether the parent is here or not.

**Comment by p0nce** [comment]
I like the name `WindowUsage` best.

**Comment by rikkimax** [comment]
@p0nce:
"This purpose cannot be inferred solely from window parenting (X11 plugin window have no parents) or listener (because at least the window test need a listener)." - you
My comment had this context.

**Comment by p0nce** [comment]
> But in saying this, why is the parent window not being passed to the implementation anyway?

I think it's because we can't add a window as a child to another since we have our own Display instance (`XOpenDisplay`). And window from different display instances are unrelated, etc. The additional callbacks from Ardour are probably to share the Display?

**Comment by p0nce** [comment]
Now the listener passed is never null, and there is a WindowUsage implementations can take to discriminate top-level windows vs child window for example (like CocoaWindow does).

This doesn't fix the inherent ugliness of conflating the two usages of Windows like that, but at least the parts that are ugly are now explicit.

For future reference:
  - Win32 windows do not differ in host and window
  - Cocoa windows are quite different in host and window
  - Carbon windows do not work as host windows
  - X11 might make good use of this explicit distinction.
