### ISSUE TITLE
Should the 'midi' module (containing e.g. MidiMessage) really be part of Dplug:client?

### ISSUE THREAD

**Issue by 0xEAB** [AuburnSounds/Dplug#228]
Should the [midi](https://github.com/0xEAB/dplug/blob/4033b34e3210d9dd2c9cd4d08930a107b005c4f4/client/dplug/client/midi.d) module really be part of *Dplug:client*? 🙈

For instance, it also makes sense to use the *MidiMessage* struct (and probably most of the other things there)
 - in **host-like** applications
 - or even abuse it for any other application that **receives or sends MIDI** (example: [voidblaster/midi-gamepad → input.d](https://github.com/voidblaster/midi-gamepad/blob/master/source/midigamepad/lib/midi/input.d)).

Of course, the current state is **not a problem**, and this is **not** urgent at all. I'm also aware that any possible change regarding this issue will be a *breaking* one.
Maybe everything is fine as-is and I'm just wrong with my assumptions.

Kind regards 😃

**Comment by p0nce** [comment]
dplug:host depends on dplug:vst which depends on dplug:client so hosts already know about MIDI messages :)

It's unavoidable that either we separate things into tiny packages and a package explosion happen, or we have more dependencies than necessary.

Also MidiMessage is a bit specialized for Dplug's use case, since it has "offset" and I think MIDI files do not. I can only quote Perlis: "Every program is a part of some other program and rarely fits"

If you are using only midi.d and it's ugly why not duplicate it?
