### ISSUE TITLE
X11Window sometimes distorts on load and causes flickering in flat-widgets

### ISSUE THREAD

**Issue by abaga129** [AuburnSounds/Dplug#350]
Most likely a race condition as @p0nce meantioned in #349.  I will work on this and try to get it sorted out quickly.

**Comment by p0nce** [comment]
A cursory reading of `x11window.d`  shows that there is very probably a race condition on `_dirtyAreasAreNotYetComputed`.

Here is my suggestion instead of your PR: protect every access to _dirtyAreasAreNotYetComputed (and associated recomputeDirtyAreas) with a regular OS mutex. It doesn't need to be the X11 display mutex, since this part doesn't interact with X11.

eg: replace 
```
_listener.recomputeDirtyAreas();
_dirtyAreasAreNotYetComputed = false;
```
by
```
_dirtyMutex.lock();
_listener.recomputeDirtyAreas();
_dirtyAreasAreNotYetComputed = false;
_dirtyMutex.unlock();
```

and replace:

```
if (_dirtyAreasAreNotYetComputed)
{
    _dirtyAreasAreNotYetComputed = false;
    _listener.recomputeDirtyAreas();
}
```
by
```
_dirtyMutex.lock();
if (_dirtyAreasAreNotYetComputed)
{
    _dirtyAreasAreNotYetComputed = false;
    _listener.recomputeDirtyAreas();
}
_dirtyMutex.unlock();
```

the purpose of that mutex is to protect that call and `_dirtyAreasAreNotYetComputed`. It should be decorrelated from `XLockDisplay` which should protect against race in something else.

(Wasn't such a problem on Win32 and other windows because possibly the timer messages wouldn't be simultaneous, but would be regular message like WM_TIMER, thus implicitely synchronized... maybe there is a problem in Cocoa like this though)

**Comment by p0nce** [comment]
Also the `timerLoop` calls `recomputeDirtyAreas` twice(!) which is entirely wrong. It should just call sendRepaintIfUIDirty

**Comment by abaga129** [comment]
I tried your suggestion and after a bit of tweaking it seems to work great. I'm going to do some more testing before making a Pull Request. Thanks a lot for looking at it.

**Comment by abaga129** [comment]
I believe both threads were trying to access `_listener`.  
Just doing
```D
_dirtyMutex.lock();
if (_dirtyAreasAreNotYetComputed)
{
    _dirtyAreasAreNotYetComputed = false;
    _listener.recomputeDirtyAreas();
}
_dirtyMutex.unlock();
```
Wasnt enough to stop the race conditions but when I changed the code inside the `Expose` event to 
```D
_dirtyMutex.lock();
if (_dirtyAreasAreNotYetComputed)
{
    _dirtyAreasAreNotYetComputed = false;
    _listener.recomputeDirtyAreas();
if(_graphicImage is null)
_graphicImage = XCreateImage(_display, _visual, depth, ZPixmap, 0, cast(char*)_wfb.pixels, _width, _height, 32, 0);
                
_listener.onDraw(WindowPixelFormat.BGRA8);
_dirtyMutex.unlock();

XPutImage(_display, _windowId, _graphicGC, _graphicImage, 0, 0, 0, 0, cast(uint)_width, cast(uint)_height);
```
It works great.

**Comment by p0nce** [comment]
Mmmm, then this hints at a race inside `_listener.onDraw` vs `_listener.recomputeDirtyAreas` (and maybe same bug as #317). I've merged your proposal (which improves things) and will open another Issue to report this remaining oddity. We've masked a bug so let's keep a trace.
