### ISSUE TITLE
Could installer support 32-bit Windows?

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#454]
Installer is not running on 32-bit Windows. Got support message from paying customer on Vista 32-bit.
Steam hardware survey says it's 0.55% but musician computers are not as up to date as gamers.

**Comment by abaga129** [comment]
I think it's possible. From what I've found on the forums this line here is probably why it won't run on 32bit windows.
https://github.com/AuburnSounds/Dplug/blob/master/tools/dplug-build/source/main.d#L1143

Then I believe NSIS has a constant that can be checked to see if it's running on 64bit.

**Comment by p0nce** [comment]
@jpcima says it works in Windows 7 32-bit, reports are vague except for one customer case who had a Vista 32-bit and sending naked plugin (no installer) solved the issue.

**Comment by jpcima** [comment]
More precisely, it worked in 7 x86, 10 x86, and 10 x64 environments.
It's these dev environments which I have locally, and there were tried both in x86-only installer and x86+x64 installer.
The highest suspicion is on Vista I guess, I'll give it a check when I can.

**Comment by p0nce** [comment]
I think if we have confidence the installer runs in 7 x86, and 10 x86, it means it likely also run in Windows 8 32-bit, which is more than sufficient for that particular bounty and also it is a remarkably low number of users. I thought there was more to do.

**Comment by jpcima** [comment]
Could not reproduce the problem in Vista 32, it worked all the same. (tried the Panagement 2 package also)
The installer ran, completed as normal, without having to explicitly run-as-admin or any actions worth noting.

Just one remark
- on 32-bit system, regardless which os version, the installer suggests to install the 64-bit version too. The pre-filled installation path of 32/64 VST is identical.
- that's kinda ok because both files are not homonymous, they're not going to conflict each other by filename
- Reaper will display a one-time message at its startup, which may be confusing. It does not not prevent the plugin from working. see capture
![message](https://user-images.githubusercontent.com/17614485/103007021-f8377f00-4532-11eb-92db-877abd5eb939.png)

**Comment by p0nce** [comment]
Ok. So stuff is working great actually. Probably this was solved by some event. Thanks for testing and I'll get back to you for bounty.
