### ISSUE TITLE
dplug:math license superscedes gfm:math license?

### ISSUE THREAD

**Issue by chances** [AuburnSounds/Dplug#613]
I'll preface this by saying, I'm not a lawyer. Please forgive me if I'm misunderstanding the license terms of `gfm:math`.

Regarding this license grant of the `gfm:math` sources:
> We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

Source: [d-gamedev-team/gfm/blob/master/UNLICENSE#L12](https://github.com/d-gamedev-team/gfm/blob/master/UNLICENSE#L12)

How does that square with this library's [BSL](https://www.boost.org/LICENSE_1_0.txt)?

Or does the "by any means" clause in [paragraph 2](https://github.com/d-gamedev-team/gfm/blob/master/UNLICENSE#L3-L6) of the Unlicense supersede "all present and future rights"?

**Comment by p0nce** [comment]
Once you copy and modify the software, it's not the same software.
So it is in my understanding that public domain software can be put under a more restrictive licence.
Besides such public domain licence do have problems, since in some juridictions (eg: France) you can relinquish your author right ever.

eg: in https://raw.githubusercontent.com/HansHammel/license-compatibility-checker/f243eb4523ebc7d019a5928103e5b82b59b3b803/licenses.svg, it is commonly accepted that public domain can be relicensed as MIT, BSD 2 or 3 clause, and Apache 2.0 

As (I think) I wrote the entirety of `gfm:math` I'm also allowed, as the copyright holder, to relicense my work under another licence.

**Comment by chances** [comment]
> Besides such public domain licence do have problems, since in some juridictions (eg: France) you can relinquish your author right ever.

This sentence is confusing. What did you mean to say here?

---

Did not we and other [contributors](https://github.com/d-gamedev-team/gfm/graphs/contributors) relinquish our copyright to the original sources under the terms of the Unlicense? If not, you are not the sole copyright holder.

Please consider acknowledging those aforementioned contributors as is done in the headers of other `dplug` packages.

**Comment by p0nce** [comment]
> This sentence is confusing. What did you mean to say here?
https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense
There are problems with public domain licences in general, which is why I've been leaning to BSL-1.0 as advised in the D newsgroup.

> Did not we and other contributors relinquish our copyright to the original sources under the terms of the Unlicense? If not, you are not the sole copyright holder.

In some juridictions you can't relinquish your copyright and still assert the licence.
https://web.archive.org/web/20170301020915/https://lists.opensource.org/pipermail/license-review/2012-January/001386.html


> Please consider acknowledging those aforementioned contributors as is done in the headers of other dplug packages.
You are absolutely right, I will add the right copyright information in each file header of dplug:math.
This is a mistake from me as GFM did not provide per-file copyright information like Dplug does, and I just forgot about the gfm:math contributions. My apologies and I will fix that.

**Comment by p0nce** [comment]
Now fixed, still it could be better since for now it can only mention github users @clinei and @drug007 by github handle, as I don't have their names.
