### ISSUE TITLE
[REQ] license settings on GH

### ISSUE THREAD

**Issue by forart** [AuburnSounds/Dplug#616]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Audio libraries > Plugins section](https://github.com/forart/HyMPS/blob/main/AudioLIBs.md#plugins)), can you please set correct licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/AuburnSounds/Dplug?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/AuburnSounds/Dplug/?label=LICENSE)

...maybe it's a GH setup issue ?

Thanks in advance.

**Comment by p0nce** [comment]
Where to set "correct" licensing terms?

**Comment by forart** [comment]
You have to create a LICENSE file:
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by p0nce** [comment]
i've added one

**Comment by forart** [comment]
It still don't generate a badge (you should choose a standard one), but thanks anyway.

**Comment by p0nce** [comment]
It does https://camo.githubusercontent.com/5a0d3fd4920995bf2fd0f395eb531fa3c07d5c5c21eeec04262f1c2b71086423/68747470733a2f2f666c61742e62616467656e2e6e65742f6769746875622f6c6963656e73652f41756275726e536f756e64732f44706c75673f6c6162656c3d
can't get a standard one since different parts of the library have wildly different licences
