### ISSUE TITLE
Crashy LV2 manifest generation

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/Dplug#661]
Large manifest tend to interrupt build on Windows + LV2.

- [x] Use some kind of Vec for manifest generation
- [x] Use some kind of C vararg function to add to it => not strictly needed
- [x] avoid all the leaks and stray mallocs
- [x] remove use of `strcat`
- [x] (optional) TTL can get big. Find a way to strip them down eventually. => can get a bit smaller with %g
Currently releasing LV2 + Windows is fraught with perils. **=> fixed**
- [x] No more size limit at all for the manifest

**Comment by PolyVector** [comment]
This might be related, but my plugin (which has many, many parameters) was crashing while generating the LV2 manifest on Linux.

The error was `malloc(): corrupted top size` on line 340 of lv2/ttl.d

This took me a while to track down, but I'm pretty sure memory is being corrupted by writing out-of-bounds into the **paramString** variable inside **buildParamPortConfiguration()**

When I increase the variable's size to 100,000, the manifest generates successfully:
`const paramStringLen = 100_000;`

Maybe this size should be based on the number of parameters? like `1_000*params.length`

This may be causing your issue on Windows as well, since memory corruption can be somewhat unpredictable.

Cheers!

**Comment by p0nce** [comment]
This needs to be rewritten with a resizeable buffer (say a Vec!char thing) and special vararg functions to add to it.

**Comment by p0nce** [comment]
Going to do this next, since we're about to exit the yearly "Dplug winter".

**Comment by p0nce** [comment]
There are still a few leaks, however it shouldn't crash anymore in v12.7.11

**Comment by p0nce** [comment]
Windows generation of large .ttl now works.

**Comment by p0nce** [comment]
@PolyVector I don't think there is bugs anymore in TTL generation. Use v12.7.12+, for both your plugin and `dplug-build` tool.

**Comment by PolyVector** [comment]
Thanks @p0nce!
