### ISSUE TITLE
when using dplug-build with --final flag, the plugin doesn't appear in the plugin list of Bitwig , ableton live, etc. DAW

### ISSUE THREAD

**Issue by rstephane** [AuburnSounds/Dplug#746]
Hello,
since few days when I execute : dplug-build -c VST3 --final
then I copy the result (the plugin) in the tight VST3 folder... then the DAW does not show up the plug in :(

but if I do dplug-build -c VST3 (without the --final flag) then it appears in the DAW ...

Any idea ? 
Thanks !

**Comment by p0nce** [comment]
Hello,

(What OS? I assume macOS. I would also like to know your `ldc2 --version` :))
I don't think too much things changed at all, strange.


## Is it --combined?
Since `--final` is equivalent to `--combined -b release-nobounds` it would be interesting to try just try:
- `dplug-build -c VST3 --combined`
- `dplug-build -c VST3 -b release-nobounds` and see what happens.


## Checking the entry points

Perhaps this line has changed (LDC may have changed its linker method) and this line doesn't work anymore in newer LDC.
```
"lflags-osx-ldc": [ "-exported_symbols_list", "source/module-vst3.lst", "-dead_strip" ],
```

You can check the built shared library that it has the necessary VST3 symbols with `nm` tools (those symbols are the ones in module-vst3.lst)

**Comment by p0nce** [comment]
Any more information about this @rstephane ? (happy new year!)
