### ISSUE TITLE
Add support for stroke in canvas

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [AuburnSounds/Dplug#780]
From what I can tell there's currently no stroke function in canvas, which makes it difficult to render line drawings of, for example, waveforms.

It would be nice if such functionality was present.

**Comment by p0nce** [comment]
Former discussion https://github.com/cerjones/dg2d/issues/2#issuecomment-639889846

**Comment by p0nce** [comment]
The way I see it would be a multi-month effort to do another rasterizer with
- 16-bit depth L16 output (since we can't remove all L16 drawing function else)
- Porter Duff operators
- Stroking

Unfortunately this dg2d fork is only well understood by its author, also dg2d is pretty quick by virtue of not having porter-duff or L16 or stroking, somehow (htough stroking is just more functionality)

**Comment by p0nce** [comment]
Finally closed with #860
